import Head from 'next/head'
import Image from 'next/image'
import Homepart0 from '@/component/Home/Homepart0'
import Homepart1 from '@/component/Home/Homepart1'
import Homepart2 from '@/component/Home/Homepart2'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Homepart0></Homepart0>
      <Homepart1></Homepart1>
      <Homepart2></Homepart2>
    </>
  )
}
